### ISSUE TITLE
[BUG] - Temp files in dist folder

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-properties#56]
**Omschrijf het probleem**
Ik merk volgende files in de dist folder:
- vl-properties.min.js.temp
- vl-properties.src.js.temp

Niet de bedoeling dat deze gecommit worden neem ik aan.

Misschien kunnen deze (dist/*.temp) ook aan gitignore worden toegevoegd?

**Comment by coemans** [comment]
@kevcraey en @pascalriquier vermoedelijk is bij deze webcomponent iets fout gelopen bij de CommonJS upgrade, dit veroorzaakt ook issue #57. @kevcraey best nog op te nemen in kader van de CommonJS upgrade?

**Comment by kevcraey** [comment]
just to be sure: probleem van de baan @driesva ?

**Comment by driesva** [comment]
@kevcraey yep
