### ISSUE TITLE
[BUG] - Import van stijl nog nodig bij minified versie?

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-properties#58]
**Omschrijf het probleem**
vl-ui-properties is geen native component dus hiervoor zou geen stijl geïmporteerd moeten worden? Het lijkt er echter op dat dit in ons geval niet voldoende is.

**Hoe te reproduceren**

In onze lit component hebben we iets zoals:
`import 'vl-ui-properties/dist/vl-properties.min.js';`

```
          <vl-properties id="publicatie-properties">
              <dl is="vl-properties-list">
                <dt is="vl-property-term">....</dt>
                <dd id="publicatie-telefoon" is="vl-property-value">
                  ...
                </dd>
```

**Screenshots**
Zonder expliciet import van de stijl:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/29454303/76495949-3cd8aa80-6438-11ea-818f-1a4adf2dbf22.png">

Met expliciete import van /node_modules/vl-ui-properties/dist/style.css is de stijl ok:

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/29454303/76496002-61cd1d80-6438-11ea-83ba-91b41fd05c0f.png">

**Omgeving (gelieve aan te vullen):**
 - Browser Chrome en Fx
 - Versie 80.0.3987.132 en 75.0b2 (64-bit)
 - Versie component 4.0.1

**Extra info**
Op het eerste zicht lijkt de stijl volledig in de minified versie te zitten.

Waarschijnlijk ligt het probleem dus aan ons gebruik?

Graag bevestiging:
- dat de (minified versie van) web component correct werkt
- dat de stijl niet  expliciet moet geïmporteerd worden

Indien de web component OK is, zullen we uiteraard zelf verder zoeken...

**Comment by coemans** [comment]
De vl-ui-properties is inderdaad geen native webcomponent en heeft een shadow DOM met interne stijl. Elementen krijgen stijl op de plaatst waar ze aangemaakt worden. In dit geval worden de native dl, dt en dd elementen niet aangemaakt in de Shadow DOM en moet de stijl op de plaatst geïmporteerd worden waar ze gedeclareerd worden.

Ter illustratie kan je naar de demo pagina kijken.

**Comment by driesva** [comment]
OK, dit is dus omwille van het slot. En in het slot zitten nog dingen die stijl krijgen van de vl-ui-properties CSS...
Dus de regel native / niet native is niet volledig. Het is dus case per case te bekijken...

Op de demo pagina is dit eigenlijk niet zo duidelijk. Tenzij je kijkt naar het feit dat de CSS daar ook geïmporteerd wordt neem ik aan.

**Comment by coemans** [comment]
De regel is: daar waar je een HTML element maakt voorzie je de stijl. Alleen in het geval van niet native varianten moet je je geen zorgen maken over de stijl van de gegenereerde inhoud. De niet native component kan onmogelijk weten wat er via een slot wordt meegegeven en is bijgevolg niet verantwoordelijk om slot elementen stijl te geven en zou zelfs niet weten welke stijl er toegepast zou moeten worden.
