### ISSUE TITLE
[BUG] - Breedte label kolom is beperkt na huisstijl upgrade

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-properties#90]
**Omschrijf het probleem**
De stijl van de vl-properties werd gewijzigd en met de nieuwe stijl is de label kolom smal waardoor de tekst wordt afgekort.

**Hoe te reproduceren**
vl-ui-properties met iets langere label

**Gewenst gedrag**
Betere benutting van de ruimte of mogelijkheid om zelf te bepalen wat de breedte mag zijn.

**Screenshots**
Voor upgrade:
![image](https://user-images.githubusercontent.com/29454303/103205842-c9d2ee80-48fa-11eb-9983-196aee9872b8.png)
Na upgrade:
![image](https://user-images.githubusercontent.com/29454303/103205858-d2c3c000-48fa-11eb-8cc2-4789b524add4.png)

Ander voorbeeld na upgrade:
![image](https://user-images.githubusercontent.com/29454303/103205882-df481880-48fa-11eb-9153-3b4885cb51b0.png)

Dit probleem doet zich ook voor op de Webuniversum site:
classic style:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/29454303/103205961-07d01280-48fb-11eb-90a0-3d587baec7dd.png">
new style:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/29454303/103205933-f8e96000-48fa-11eb-8d50-36897efdeffe.png">

**Omgeving:**
 - Browser Fx developer 5.0b4 (64-bit) , Edge 87.0.664.66
 - Versie component 4.0.8

**Comment by coemans** [comment]
Ik zal intern informeren naar mogelijke oplossingen voor dit probleem.

**Comment by coemans** [comment]
Ik heb centraal een voorstel gedaan om een breedte tot maximaal 25% in te laten nemen. Vroeger werd 30% gebruikt, maar in de nieuwe stijl is de content minimaal 75%. Door een stijl probleem nam het label echter slechts maximaal 17rem in beslag i.p.v. 25%.
